### ISSUE TITLE
Implement feature selection

### ISSUE THREAD

**Issue by grst** [scverse/multi-condition-comparisions#17]
### Description of feature

e.g. adopt edge R's `filterByExpr`. There's already an implementation in decoupler: https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html#Pseudo-bulk-profile-gene-filtering

**Comment by Zethson** [comment]
There's also `filter_by_prop` in decoupler. I'll add them directly to pertpy since we have decoupler as a dependency anyways and then we can make use of it later

**Comment by Zethson** [comment]
Note that for the MVP we can just call decoupler in this repository
