### ISSUE TITLE
Ready to be used?

### ISSUE THREAD

**Issue by SNOL2** [scverse/multi-condition-comparisions#42]
### Description of feature

Hi, this tool looks like a great way to perform pseudo-bulk DEA. May I asked how is the development progress and whether it is ready to be used! 
Thanks!

**Comment by grst** [comment]
Hi @SNOL2, 

thanks for your interest in this package. It's not quite ready. There is still #36 to be merged and there is currently no up-to-date documentation. 

Once #36, we will start migrating the code into [pertpy](https://github.com/theislab/pertpy) where the production version of this package will live. 

That said, the basic functionality is there, and we are always happy about feedback if you want to give it a try! 

Cheers, 
Gregor
